# Generated by Django 4.2.7 on 2023-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('researcher_id', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('institutes', models.ManyToManyField(blank=True, related_name='researchers', to='institutes.institute')),
            ],
        ),
    ]
