# Generated by Django 4.2.7 on 2023-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
        ('researcher', '0002_researcher_citation_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='institutes',
            field=models.ManyToManyField(blank=True, related_name='institutes', to='institutes.institute'),
        ),
    ]
