# Generated by Django 4.2.7 on 2023-11-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('dissemination_medium', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('article', 'Article'), ('book', 'Published Book'), ('chapter', 'Published Chapter')], max_length=20)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.production')),
                ('periodical_title', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_location', models.CharField(max_length=255)),
                ('homepage', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedBook',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.production')),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedChapter',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.production')),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('organizers', models.TextField()),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
