# Generated by Django 4.2.7 on 2023-11-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('dissemination_medium', models.CharField(max_length=50)),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('organizers', models.TextField()),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('dissemination_medium', models.CharField(max_length=50)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('dissemination_medium', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=255)),
                ('event_city', models.CharField(max_length=255)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_name', models.CharField(max_length=255)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('dissemination_medium', models.CharField(max_length=50)),
                ('periodical_title', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_location', models.CharField(max_length=255)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
