# Generated by Django 4.2.7 on 2023-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_researcher_citation_names'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='researcher.researcher'),
        ),
    ]
