# Generated by Django 4.2.7 on 2023-11-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_production_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Article'), (2, 'Published Book'), (2, 'Published Chapter')]),
        ),
    ]
