# Generated by Django 4.2.7 on 2023-11-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_production_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Article'), (2, 'Published Book'), (3, 'Published Chapter')]),
        ),
    ]
